# spring.application.name=second
server:
  port: 8084

spring:

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: JPA
    password: tiger

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
